### ISSUE TITLE
Merge improvements from BA-4chan-thread-archiver

### ISSUE THREAD

**Issue by JamesJebson** [bibanon/BASC-Archiver#15]
Using https://github.com/bibanon/BA-4chan-thread-archiver you get a HTML with inline picture viewing, quote previews when hovering on a link.

The only thing that isn't working on https://github.com/bibanon/BA-4chan-thread-archiver is the thumbnails.

Is there a chance of bringing those features (in-line image viewing, quote hovering) into the current BASC-Archiver?

**Comment by antonizoon** [comment]
Hmm? Do you imply that there is no such feature in the BASC-Archiver?

The BA-4chan-thread-archiver is completely depreciated. It is just a legacy symlink to the BASC-Archiver, since out of tradition we never break legacy links. I think we may have forgotten to push the thumbnail fixing code to that old package, but it shouldn't be used in the first place.

With the HTML, we literally grab whatever's on 4chan's servers. What they have is what you get. In fact, when I get the time I will use direct JSON templating instead of scraping HTML, it reduces the load. (Though we will retain an option to grab original HTML/CSS when the mods screw with /b/).

Now if the BASC-Archiver is failing to grab JS, that is a bug, probably because the URLs changed.

**Comment by JamesJebson** [comment]
Yes, BA-4chan includes all the inline viewing that the JS would provide but BASC doesn't. I have two threads archived from /g/ today, using each archiver script. Would you like me to upload them somewhere so you can see better what I mean?

**Comment by plueschopath** [comment]
Can confirm. It seems that just the js isn't dumped.

**Comment by DanielOaks** [comment]
Will have a look at this – thanks for the report!

**Comment by JamesJebson** [comment]
Great! No problem, thanks for looking at it.

**Comment by DanielOaks** [comment]
This is now fixed, some silly regex was being needlessly specific. Commit https://github.com/bibanon/BASC-Archiver/commit/0abbdd5ee9a56607aa5c8f23e3ce2e6efb58537f specifically.

Released 0.8.7, pushed to PyPi.

**Comment by antonizoon** [comment]
Make sure to release the changes to the BA-4chan-thread-archiver package as well, we often neglect it. Thanks.
